Repository fianlProjectTeam2/server, pull requests merged in 2025-01, with the labels that each got.

#25 Feature/1/news craw
  finalProject/.gitignore
  finalProject/src/main/java/finalProject/API/StockInfoAPI.java
  finalProject/src/main/java/finalProject/CorsConfig.java
  finalProject/src/main/java/finalProject/controller/LoginController.java
  finalProject/src/main/java/finalProject/service/craw/CrawService.java
  finalProject/src/main/java/finalProject/service/login/SessionCheckService.java
Labels: :hammer: feature

#27 🔨feature : 크롤링한 뉴스 DB 저장
  finalProject/src/main/java/finalProject/controller/CrawController.java
  finalProject/src/main/java/finalProject/domain/craw/CrawDTO.java
  finalProject/src/main/java/finalProject/mapper/CrawMapper.java
  finalProject/src/main/java/finalProject/service/craw/CrawDbSaveService.java
  finalProject/src/main/resources/mappers/CrawMapper.xml
Labels: :hammer: feature

#30 🔨feature : 주식 정보 DB에 저장
  finalProject/src/main/java/finalProject/controller/StockInfoController.java
  finalProject/src/main/java/finalProject/domain/stock/StockDTO.java
  finalProject/src/main/java/finalProject/mapper/StockMapper.java
  finalProject/src/main/java/finalProject/service/Stock/StockDBService.java
  finalProject/src/main/java/finalProject/service/Stock/StockInfoService.java
  finalProject/src/main/resources/mappers/StockMapper.xml
Labels: :hammer: feature

#34 🔨 Feature/19/comment
  finalProject/src/main/java/finalProject/command/CommentCommand.java
  finalProject/src/main/java/finalProject/command/PostCommand.java
  finalProject/src/main/java/finalProject/controller/CommentController.java
  finalProject/src/main/java/finalProject/controller/PostController.java
  finalProject/src/main/java/finalProject/domain/CommentDTO.java
  finalProject/src/main/java/finalProject/mapper/MemberMapper.java
  finalProject/src/main/java/finalProject/mapper/PostLikeMapper.java
  finalProject/src/main/java/finalProject/mapper/PostMapper.java
  finalProject/src/main/java/finalProject/service/post/PostDetailService.java
  finalProject/src/main/java/finalProject/service/post/PostLikeService.java
  finalProject/src/main/java/finalProject/service/post/PostWriteService.java
  finalProject/src/main/resources/mappers/MemberMapper.xml
  finalProject/src/main/resources/mappers/PostLikeMapper.xml
  finalProject/src/main/resources/mappers/PostMapper.xml
  finalProject/src/main/resources/mappers/UserMapper.xml
  finalProject/src/main/resources/static/css/post/postInfo.css
  finalProject/src/main/resources/templates/thymeleaf/post/postForm.html
  finalProject/src/main/resources/templates/thymeleaf/post/postInfo.html
  finalProject/src/main/resources/templates/thymeleaf/post/postModify.html
Labels: :hammer: feature

#35 🔨 feature : GPT 요청 / 응답 기능 추가
  finalProject/pom.xml
  finalProject/src/main/java/finalProject/API/GPT/ChatGPTRequest.java
  finalProject/src/main/java/finalProject/API/GPT/ChatGPTResponse.java
  finalProject/src/main/java/finalProject/API/GPT/GPTApiClient.java
  finalProject/src/main/java/finalProject/API/GPT/GPTMessage.java
  finalProject/src/main/java/finalProject/PropertyConfig.java
  finalProject/src/main/java/finalProject/controller/GPTController.java
  finalProject/src/main/java/finalProject/service/gpt/ArticlePredictionService.java
  finalProject/src/main/java/finalProject/service/gpt/GPTType.java
  finalProject/src/main/java/finalProject/service/gpt/PreTrainingService.java
  finalProject/src/main/resources/static/prompts/article-prompt.json
Labels: :hammer: feature

#37 🔨 feature : 예측 안된 기사 목록 출력 기능 추가
  finalProject/src/main/java/finalProject/domain/article/ArticleDTO.java
  finalProject/src/main/java/finalProject/mapper/ArticleMapper.java
  finalProject/src/main/java/finalProject/service/admin/StartEndPageService.java
  finalProject/src/main/java/finalProject/service/article/UnexpectedArticleService.java
  finalProject/src/main/resources/mappers/ArticleMapper.xml
Labels: :hammer: feature

#40 🔨 Feature/31/member/account
  finalProject/.gitignore
  finalProject/src/main/java/finalProject/controller/AccountController.java
  finalProject/src/main/java/finalProject/controller/LoginController.java
  finalProject/src/main/java/finalProject/mapper/AccountMapper.java
  finalProject/src/main/java/finalProject/service/account/AccountPointChargeService.java
  finalProject/src/main/resources/templates/thymeleaf/react/LoginForReact.html
  finalProject/src/main/resources/templates/thymeleaf/react/reactLogin.html
Labels: :hammer: feature

#42 📝chore: 유저 ID로 유저번호 가져오는 기능 추가
  finalProject/src/main/java/finalProject/mapper/UserMapper.java
  finalProject/src/main/resources/mappers/UserMapper.xml
Labels: :memo: chore

#45 🔨 feature: 기사 예측 기능 완료.
  finalProject/src/main/java/finalProject/API/GPT/GPTApiClient.java
  finalProject/src/main/java/finalProject/controller/GPTController.java
  finalProject/src/main/java/finalProject/domain/ArticlePredictionDTO.java
  finalProject/src/main/java/finalProject/mapper/ArticleMapper.java
  finalProject/src/main/java/finalProject/service/article/UnexpectedArticleService.java
  finalProject/src/main/java/finalProject/service/gpt/ArticlePredictionService.java
  finalProject/src/main/resources/mappers/ArticleMapper.xml
  finalProject/src/main/resources/static/prompts/article-prompt.json
Labels: :memo: chore

#49 Feature/19/comment
  finalProject/src/main/java/finalProject/command/CommentCommand.java
  finalProject/src/main/java/finalProject/controller/CommentController.java
  finalProject/src/main/java/finalProject/controller/PostController.java
  finalProject/src/main/java/finalProject/domain/CommentDTO.java
  finalProject/src/main/java/finalProject/mapper/CommentMapper.java
  finalProject/src/main/java/finalProject/service/post/CommentDeleteService.java
  finalProject/src/main/java/finalProject/service/post/CommentListService.java
  finalProject/src/main/java/finalProject/service/post/CommentWriteService.java
  finalProject/src/main/java/finalProject/service/post/PostDetailService.java
  finalProject/src/main/java/finalProject/service/post/PostLikeService.java
  finalProject/src/main/resources/mappers/CommentMapper.xml
  finalProject/src/main/resources/mappers/PostMapper.xml
  finalProject/src/main/resources/static/css/post/postInfo.css
  finalProject/src/main/resources/templates/thymeleaf/post/postForm.html
  finalProject/src/main/resources/templates/thymeleaf/post/postInfo.html
  finalProject/src/main/resources/templates/thymeleaf/post/postList.html
Labels: :hammer: feature

#52 📝chore : 삭제된 파일 추가
  finalProject/.gitignore
  finalProject/src/main/java/finalProject/API/StockInfo/StockInfoAPI.java
  finalProject/src/main/java/finalProject/controller/CrawController.java
  finalProject/src/main/java/finalProject/service/Stock/StockDBService.java
  finalProject/src/main/java/finalProject/service/Stock/StockInfoService.java
  finalProject/src/main/java/finalProject/service/craw/CrawServices.java
Labels: :memo: chore

#53 UI update/50/UI update
  finalProject/src/main/resources/static/css/footer2.css
  finalProject/src/main/resources/static/css/header2.css
  finalProject/src/main/resources/static/css/post/postList.css
  finalProject/src/main/resources/static/css/title/dropDown.css
  finalProject/src/main/resources/static/css/title/memberList.css
  finalProject/src/main/resources/static/css/title/titleInfo.css
  finalProject/src/main/resources/templates/thymeleaf/admin/adminForm.html
  finalProject/src/main/resources/templates/thymeleaf/admin/adminHome.html
  finalProject/src/main/resources/templates/thymeleaf/admin/titleList.html
  finalProject/src/main/resources/templates/thymeleaf/admin/titleWrite.html
  finalProject/src/main/resources/templates/thymeleaf/member/memberForm.html
  finalProject/src/main/resources/templates/thymeleaf/member/memberList.html
  finalProject/src/main/resources/templates/thymeleaf/post/postForm.html
  finalProject/src/main/resources/templates/thymeleaf/post/postIndex.html
  finalProject/src/main/resources/templates/thymeleaf/post/postInfo.html
  finalProject/src/main/resources/templates/thymeleaf/post/postList.html
  finalProject/src/main/resources/templates/thymeleaf/post/postModify.html
Labels: :lipstick: UI Update

#55 🔨 feature : 알림 등록 및 리스트
  finalProject/src/main/java/finalProject/command/AlertCommand.java
  finalProject/src/main/java/finalProject/controller/AlertController.java
  finalProject/src/main/java/finalProject/domain/AlertDTO.java
  finalProject/src/main/java/finalProject/domain/AlertListDTO.java
  finalProject/src/main/java/finalProject/mapper/AlertMapper.java
  finalProject/src/main/java/finalProject/service/admin/AlertAutoNumService.java
  finalProject/src/main/java/finalProject/service/admin/AlertDeleteService.java
  finalProject/src/main/java/finalProject/service/admin/AlertListService.java
  finalProject/src/main/java/finalProject/service/admin/AlertWriteService.java
  finalProject/src/main/resources/mappers/AlertMapper.xml
  finalProject/src/main/resources/templates/thymeleaf/admin/alertList.html
  finalProject/src/main/resources/templates/thymeleaf/admin/alertRedirect.html
  finalProject/src/main/resources/templates/thymeleaf/admin/alertWrite.html
Labels: :hammer: feature

#57 Feature/31/member/account
  finalProject/src/main/java/finalProject/controller/StockPurchaseController.java
  finalProject/src/main/java/finalProject/domain/stock/CumulativeStockDTO.java
  finalProject/src/main/java/finalProject/domain/stock/SellDTO.java
  finalProject/src/main/java/finalProject/mapper/StockMapper.java
  finalProject/src/main/java/finalProject/service/Stock/StockPurchaseInfoService.java
  finalProject/src/main/java/finalProject/service/Stock/StockPurchaseService.java
  finalProject/src/main/java/finalProject/service/Stock/StockSellService.java
  finalProject/src/main/resources/mappers/StockMapper.xml
Labels: :hammer: feature

#59 🔨 feature : Kafka 기능 구현 완료
  finalProject/pom.xml
  finalProject/src/main/java/finalProject/API/kafka/BroadCastServer.java
  finalProject/src/main/java/finalProject/API/kafka/KafkaConsumerServer.java
  finalProject/src/main/java/finalProject/API/kafka/KafkaStreamsServer.java
  finalProject/src/main/java/finalProject/API/kafka/MultiThreadedUDPServer.java
  finalProject/src/main/java/finalProject/API/kafka/RawStockConsumer.java
  finalProject/src/main/java/finalProject/API/kafka/StockA3.java
  finalProject/src/main/java/finalProject/API/kafka/StockStatistics.java
  finalProject/src/main/java/finalProject/API/socket/KafkaWebSocketHandler.java
  finalProject/src/main/java/finalProject/API/socket/WebSocketClientConnector.java
  finalProject/src/main/java/finalProject/FinalProjectApplication.java
  finalProject/src/main/java/finalProject/config/WebSocketConfig.java
  finalProject/src/main/java/finalProject/controller/KafkaController.java
  finalProject/src/main/java/finalProject/domain/KafkaStockDTO.java
  finalProject/src/main/java/finalProject/mapper/KafkaMapper.java
  finalProject/src/main/java/finalProject/service/kafka/ConsumerStartService.java
  finalProject/src/main/java/finalProject/service/kafka/InsertDealService.java
  finalProject/src/main/java/finalProject/service/kafka/ProducerStartService.java
  finalProject/src/main/java/finalProject/service/kafka/StreamsStartService.java
  finalProject/src/main/resources/application.properties
  finalProject/src/main/resources/mappers/KafkaMapper.xml
Labels: :hammer: feature

#60 🔨feature :수익 랭킹
  finalProject/src/main/java/finalProject/controller/RankController.java
  finalProject/src/main/java/finalProject/domain/rank/RankDTO.java
  finalProject/src/main/java/finalProject/mapper/RankMapper.java
  finalProject/src/main/java/finalProject/service/rank/RankInsertService.java
  finalProject/src/main/java/finalProject/service/rank/RankSelectService.java
  finalProject/src/main/resources/mappers/RankMapper.xml
Labels: :hammer: feature

#62 Feature/56/inquire
  finalProject/src/main/java/finalProject/command/AnswerCommand.java
  finalProject/src/main/java/finalProject/command/InquireCommand.java
  finalProject/src/main/java/finalProject/controller/AnswerController.java
  finalProject/src/main/java/finalProject/controller/InquireController.java
  finalProject/src/main/java/finalProject/controller/StockInfoController.java
  finalProject/src/main/java/finalProject/domain/AnswerDTO.java
  finalProject/src/main/java/finalProject/domain/InquireDTO.java
  finalProject/src/main/java/finalProject/mapper/AnswerMapper.java
  finalProject/src/main/java/finalProject/mapper/InquireMapper.java
  finalProject/src/main/java/finalProject/service/inquire/InquireDetailService.java
  finalProject/src/main/java/finalProject/service/inquire/InquireListService.java
  finalProject/src/main/java/finalProject/service/inquire/InquireUpdateService.java
  finalProject/src/main/java/finalProject/service/inquire/InquireWriteService.java
  finalProject/src/main/resources/mappers/AnswerMapper.xml
  finalProject/src/main/resources/mappers/InquireMapper.xml
  finalProject/src/main/resources/templates/thymeleaf/index.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireForm.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireInfo.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireList.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireModify.html
  finalProject/src/main/resources/templates/thymeleaf/post/postInfo.html
Labels: :hammer: feature

#68 UI update/67/menu integration
  finalProject/src/main/resources/templates/thymeleaf/admin/adminForm.html
  finalProject/src/main/resources/templates/thymeleaf/admin/adminHome.html
  finalProject/src/main/resources/templates/thymeleaf/admin/alertList.html
  finalProject/src/main/resources/templates/thymeleaf/admin/alertWrite.html
  finalProject/src/main/resources/templates/thymeleaf/admin/titleList.html
  finalProject/src/main/resources/templates/thymeleaf/admin/titleWrite.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireForm.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireInfo.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireList.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireModify.html
  finalProject/src/main/resources/templates/thymeleaf/member/memberForm.html
  finalProject/src/main/resources/templates/thymeleaf/member/memberList.html
  finalProject/src/main/resources/templates/thymeleaf/post/postForm.html
  finalProject/src/main/resources/templates/thymeleaf/post/postInfo.html
  finalProject/src/main/resources/templates/thymeleaf/post/postList.html
  finalProject/src/main/resources/templates/thymeleaf/post/postModify.html
Labels: :lipstick: UI Update

#69 bug/58/상단 바 이동 오류
  finalProject/src/main/java/finalProject/controller/MoveController.java
  finalProject/src/main/java/finalProject/mapper/StockMapper.java
  finalProject/src/main/java/finalProject/service/Stock/StockMyFinancesService.java
  finalProject/src/main/java/finalProject/service/craw/CrawServices.java
  finalProject/src/main/java/finalProject/service/move/MoveService.java
  finalProject/src/main/resources/mappers/StockMapper.xml
  finalProject/src/main/resources/static/prompts/article-prompt.json
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireForm.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireInfo.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireList.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireModify.html
  finalProject/src/main/resources/templates/thymeleaf/post/postList.html
  finalProject/src/main/resources/templates/thymeleaf/post/postModify.html
Labels: :bug: bug

#71 🔨 feature : kafka 토픽 분리
  finalProject/src/main/java/finalProject/API/kafka/KafkaConsumerServer.java
  finalProject/src/main/java/finalProject/API/kafka/MultiThreadedUDPServer.java
  finalProject/src/main/java/finalProject/API/kafka/RawStockConsumer.java
  finalProject/src/main/java/finalProject/API/socket/ChatHandshakeInterceptor.java
  finalProject/src/main/java/finalProject/API/socket/ChattingSocketServer.java
  finalProject/src/main/java/finalProject/config/WebSocketConfig.java
  finalProject/src/main/java/finalProject/controller/ChatController.java
  finalProject/src/main/java/finalProject/controller/GPTController.java
  finalProject/src/main/resources/templates/thymeleaf/chat/chatTest.html
Labels: :hammer: feature

#74 Feature/58/ranking
  finalProject/src/main/java/finalProject/API/kafka/KafkaConsumerServer.java
  finalProject/src/main/java/finalProject/API/kafka/KafkaStreamsServer.java
  finalProject/src/main/java/finalProject/config/WebSocketConfig.java
  finalProject/src/main/java/finalProject/controller/CrawController.java
  finalProject/src/main/java/finalProject/controller/StockInfoController.java
  finalProject/src/main/java/finalProject/domain/craw/CrawDTO.java
  finalProject/src/main/java/finalProject/domain/stock/ChartDTO.java
  finalProject/src/main/java/finalProject/mapper/CrawMapper.java
  finalProject/src/main/java/finalProject/mapper/StockMapper.java
  finalProject/src/main/java/finalProject/service/Stock/StockChartDataService.java
  finalProject/src/main/java/finalProject/service/Stock/StockDefaultDataService.java
  finalProject/src/main/java/finalProject/service/craw/CrawDbSaveService.java
  finalProject/src/main/java/finalProject/service/craw/CrawServices.java
  finalProject/src/main/resources/mappers/CrawMapper.xml
  finalProject/src/main/resources/mappers/StockMapper.xml
Labels: :hammer: feature

#76 🔨feature : 뉴스 분석 점수
  finalProject/src/main/java/finalProject/controller/CrawController.java
  finalProject/src/main/java/finalProject/domain/craw/CrawDTO.java
  finalProject/src/main/java/finalProject/mapper/CrawMapper.java
  finalProject/src/main/java/finalProject/service/craw/CrawPredictionScoreService.java
  finalProject/src/main/java/finalProject/service/craw/CrawPredictionService.java
  finalProject/src/main/resources/mappers/CrawMapper.xml
Labels: :hammer: feature

#78 🔨feature: 게시판 문의 팝업버튼 추가 완료
  finalProject/src/main/resources/static/css/header2.css
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireForm.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireInfo.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireList.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireModify.html
  finalProject/src/main/resources/templates/thymeleaf/post/postForm.html
  finalProject/src/main/resources/templates/thymeleaf/post/postInfo.html
  finalProject/src/main/resources/templates/thymeleaf/post/postList.html
  finalProject/src/main/resources/templates/thymeleaf/post/postModify.html
Labels: :hammer: feature

#82 Feature/81/admin post delete
  finalProject/src/main/java/finalProject/command/CommentCommand.java
  finalProject/src/main/java/finalProject/command/PostCommand.java
  finalProject/src/main/java/finalProject/controller/AnswerController.java
  finalProject/src/main/java/finalProject/controller/PostController.java
  finalProject/src/main/java/finalProject/domain/CommentDTO.java
  finalProject/src/main/java/finalProject/domain/PostDTO.java
  finalProject/src/main/java/finalProject/mapper/InquireMapper.java
  finalProject/src/main/java/finalProject/mapper/PostMapper.java
  finalProject/src/main/java/finalProject/service/StartEndPageService.java
  finalProject/src/main/java/finalProject/service/inquire/InquireDeleteService.java
  finalProject/src/main/java/finalProject/service/post/PostDeleteService.java
  finalProject/src/main/resources/mappers/InquireMapper.xml
  finalProject/src/main/resources/mappers/PostMapper.xml
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireForm.html
  finalProject/src/main/resources/templates/thymeleaf/inquire/inquireModify.html
  finalProject/src/main/resources/templates/thymeleaf/post/postInfo.html
  finalProject/src/main/resources/templates/thymeleaf/post/postList.html
Labels: :hammer: feature

#85 🔨feature: 관리자에게 댓글삭제 권한부여, 추천버튼, 댓글창 숨김
  finalProject/src/main/resources/templates/thymeleaf/post/postInfo.html
Labels: :memo: chore

#86 🔨feature : 회원 알림 제공 및 확인
  finalProject/src/main/java/finalProject/controller/AlertController.java
  finalProject/src/main/java/finalProject/mapper/AlertMapper.java
  finalProject/src/main/java/finalProject/service/alert/AlertCheckService.java
  finalProject/src/main/resources/mappers/AlertMapper.xml
Labels: :hammer: feature

#89 🔨feature : 수익률
  finalProject/src/main/java/finalProject/controller/RankController.java
  finalProject/src/main/java/finalProject/mapper/RankMapper.java
  finalProject/src/main/java/finalProject/service/rank/RankProfitService.java
  finalProject/src/main/resources/mappers/RankMapper.xml
Labels: :hammer: feature
